[package]
name = "webdav_server"
version = "0.1.0"
authors = ["Matthew Brewer <mbrewer@smalladventures.net>"]
edition = "2018"

[dependencies]
hyper = { path = "../hyper" }
webdav = { path = "../webdav" }
pretty_env_logger = "0.3"
tokio = "0.1"
tokio-fs = "0.1"
futures = "0.1.21"
